---

system_packages_extra:
  - binutils
  - gcc
  - make
  - patch
  - libgomp
  - glibc-headers
  - glibc-devel
  - kernel-headers
  - kernel-devel
  - dkms
  - VirtualBox-5.2

url_packages:
  - https://downloads.slack-edge.com/linux_releases/slack-3.2.0.beta25a7a50e-0.1.fc21.x86_64.rpm

repositories:
  - http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
