# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "generic/fedora27"
  config.vm.network "private_network", ip: "192.168.87.223"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.synced_folder "../..", "/playbook", nfs: true
  config.vm.provision "shell", inline: "sudo dnf -y install ansible"
end
